{
 "title": "Dash Forum API",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\",application=\"$application\"}, pool)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API uptime",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", job=\"app-forum-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "Pool de conexões JDBC",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB timeout",
   "type": "stat",
   "description": "Conexões com o database em timeout",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"$job\", pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "timeseries",
   "description": "Estado das conexões com database",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Hora da inicialização da API",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users logged",
   "type": "stat",
   "description": "Usuários logados no último minuto",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Errors",
   "type": "stat",
   "description": "Erros de autenticação no último minuto",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warn & Error Log",
   "type": "timeseries",
   "description": "Warning e erros logados nos últimos 5 minutos",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[$__rate_interval]))",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[$__rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "description": "Memória heap utilizada",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"$job\", area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"$job\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "System CPU usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Process CPU usage"
    }
   ]
  },
  {
   "title": "NON-HEAP USED",
   "type": "gauge",
   "description": "Memória non-heap utilizada",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"$job\", area=\"nonheap\"}) * 100) / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"$job\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE",
   "type": "timeseries",
   "description": "Média de uso da CPU",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "CPU core size"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Número de erros 500 nos últimos 5 minutos",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests/s",
   "type": "stat",
   "description": "Número de requisições no último minuto",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "Latência média por minuto",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Taxa de erros nos últimos 5 minutos",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Tempo de resposta no último minuto",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Número de requisições por endpoint no último minuto",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri=\"/topicos\"}[5m]))",
     "legendFormat": "/topicos"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri=\"/topicos/{id}\"}[5m]))",
     "legendFormat": "/topicos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", uri=\"/auth\"}[5m]))",
     "legendFormat": "/auth"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração média de requisições no último minuto",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/topicos\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri=\"/auth\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração máxima de uma requisição",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"$job\", status=\"200\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  }
 ]
}